// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      // Add more cases for other platforms.
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPgHpBRmIim4EaI2WyEz0uibluAklUag8',
    appId: '1:417621766874:web:6d36f6335a932cd139abe3',
    messagingSenderId: '417621766874',
    projectId: 'inventary-34691',
    authDomain: 'inventary-34691.firebaseapp.com',
    storageBucket: 'inventary-34691.appspot.com',
    measurementId: 'G-B3K6LVNP63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0HjnjWimc_TSeETVm_qibT_PhYzA_q5w',
    appId: '1:417621766874:android:a5e1ec64c8bb85df39abe3',
    messagingSenderId: '417621766874',
    projectId: 'inventary-34691',
    storageBucket: 'inventary-34691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ9L7DZYgSv5GeQrCI5hm8VTvhN2tDk3I',
    appId: '1:417621766874:ios:63dc972c031aa07139abe3',
    messagingSenderId: '417621766874',
    projectId: 'inventary-34691',
    storageBucket: 'inventary-34691.appspot.com',
    iosClientId:
        '417621766874-hfhh84jo837ng6ag28q9t2h7deqea80c.apps.googleusercontent.com',
    iosBundleId: 'delivery',
  );
}
